import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { ZoomProvider } from "@/context/ZoomContext";
import PageTransition from "@/components/ui/PageTransition";

const latoFont = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Tehnoplast",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <ZoomProvider>
        <html lang={locale}>
          <body className={`${latoFont.variable} antialiased`}>
            <PageTransition />
            {children}
          </body>
        </html>
      </ZoomProvider>
    </NextIntlClientProvider>
  );
}
